/**
 * Suburb data for /areas/[suburb] pages.
 *
 * Each entry has enough real, per-suburb detail that Google reads the pages
 * as unique content rather than a templated variant. The template
 * (src/app/areas/[suburb]/page.tsx) reads from these fields — landmark,
 * housing stock, common install, council, local hooks, and a nearby-suburb
 * chip list — so no two pages produce the same body copy.
 *
 * `published: true` gates which suburbs land in generateStaticParams +
 * sitemap. Rolls out in waves so we don't dump 42 URLs on Google at once.
 * See scratchpad/seo-plan-v2.html for the wave schedule.
 */

export type Suburb = {
  slug: string;
  name: string;
  postcode: string;
  distanceKm: number;
  published: boolean;
  council: string;
  landmark: string;
  housingStock: string;
  commonInstall: string;
  localHooks: string[];
  testimonial?: {
    who: string;
    what: string;
    quote: string;
  };
  nearby: string[];
};

export const suburbs: Suburb[] = [
  {
    slug: "pakenham",
    name: "Pakenham",
    postcode: "3810",
    distanceKm: 0,
    published: true,
    council: "Cardinia Shire Council",
    landmark: "Toomuc Creek and the Pakenham Racecourse sit in the middle of our service radius",
    housingStock:
      "a mix of original Main Street cottages, the 90s Cameron Park brick estates and the newer Lakeside and Arena estates on the north side",
    commonInstall:
      "Reclaim R290 heat pumps replacing 15-year-old Rinnai gas storage tanks in Cameron Park, and full Mitsubishi Electric ducted retrofits in the Lakeside two-storeys",
    localHooks: [
      "Cardinia Cultural Centre",
      "Pakenham Consolidated Primary",
      "James Bathe Reserve",
      "the Deep Creek Reserve behind Lakeside",
    ],
    testimonial: {
      who: "Jess M., Pakenham",
      what: "Reclaim heat pump swap, VEU rebate handled",
      quote:
        "Took the old Rinnai out, dropped in a Reclaim heat pump, sorted the VEU rebate so I paid less than $400 out of pocket. The bloke on the phone was the bloke on the tools — refreshing.",
    },
    nearby: ["officer", "beaconsfield", "pakenham-upper", "nar-nar-goon", "tynong", "bunyip"],
  },
  {
    slug: "officer",
    name: "Officer",
    postcode: "3809",
    distanceKm: 6,
    published: true,
    council: "Cardinia Shire Council",
    landmark: "the Arena Shopping Centre and the new Officer Central precinct off Rix Road",
    housingStock:
      "predominantly newer estate homes — Timbertop, Arcadia, Beacon Hills — most built inside the last decade with ducted heating and cooling already roughed in",
    commonInstall:
      "clean ducted aircon installs into new-build cavities, and VEU-eligible heat pump swaps as the original electric storage tanks that came with the estate homes hit end-of-life",
    localHooks: [
      "Officer Primary School",
      "St Brigid's Catholic Primary",
      "Officer Recreation Reserve",
      "the Bee-Line commuter service on Princes Highway",
    ],
    testimonial: {
      who: "Dean R., Officer",
      what: "Mitsubishi ducted retrofit — Arcadia estate",
      quote:
        "Had three quotes for a ducted system. These guys were the only ones who actually crawled into the roof. Middle of the pack on price but installed cleaner than the others would have.",
    },
    nearby: ["pakenham", "beaconsfield", "berwick", "cardinia-town", "narre-warren"],
  },
  {
    slug: "beaconsfield",
    name: "Beaconsfield",
    postcode: "3807",
    distanceKm: 10,
    published: true,
    council: "Cardinia Shire Council",
    landmark: "the Old Beaconsfield township along Woods Street and Berwick Grammar's Beaconsfield campus",
    housingStock:
      "large-block older weatherboards on the north side, and the newer Ellenbrook and Coach estate builds south of the highway",
    commonInstall:
      "gas ducted heating replacements — usually Brivis or Braemar rip-out and swap — plus Mitsubishi MSZ-AP splits in the weatherboards where ducted isn't feasible",
    localHooks: [
      "Beaconsfield Primary School",
      "Berwick Grammar (Beaconsfield campus)",
      "the Cardinia Creek Rail Trail",
      "Beaconsfield Reserve",
    ],
    nearby: ["berwick", "officer", "pakenham", "beaconsfield-upper", "narre-warren"],
  },
  {
    slug: "berwick",
    name: "Berwick",
    postcode: "3806",
    distanceKm: 14,
    published: true,
    council: "City of Casey",
    landmark: "Wilson Botanic Park and the heritage Old Berwick Village shopping strip on High Street",
    housingStock:
      "a real split between the Old Berwick weatherboards on the hill, the 2000s Timbarra brick veneer estates south of the highway, and the newer Lakeside apartments",
    commonInstall:
      "Mitsubishi MSZ-AP wall splits into the older stock where a single unit does the living zone, and full ducted retrofits into the double-storey Timbarra homes",
    localHooks: [
      "Wilson Botanic Park",
      "Nossal High School",
      "Berwick Primary",
      "St Margaret's Berwick Grammar",
      "Casey Hospital",
    ],
    testimonial: {
      who: "Sam K., Berwick",
      what: "Emergency hot water — iStore heat pump replacement",
      quote:
        "Hot water died on a Sunday with three kids in the house. Answered the phone, had a temp loaner running by lunch, new iStore in on Tuesday. That's service.",
    },
    nearby: ["officer", "narre-warren", "endeavour-hills", "cranbourne", "beaconsfield"],
  },
  {
    slug: "narre-warren",
    name: "Narre Warren",
    postcode: "3805",
    distanceKm: 20,
    published: true,
    council: "City of Casey",
    landmark: "Westfield Fountain Gate and the Casey RACE aquatic centre on Magid Drive",
    housingStock:
      "predominantly 90s brick veneer family homes on quarter-acre blocks, with pockets of newer townhouse infill closer to Fountain Gate",
    commonInstall:
      "bedroom split system upgrades — usually two-to-three-head Mitsubishi Electric multi-heads — plus like-for-like gas storage hot water swaps in the original estate builds",
    localHooks: [
      "Westfield Fountain Gate",
      "Casey Complex",
      "Narre Warren Railway Station",
      "Fleetwood Primary",
      "Fountain Gate Secondary",
    ],
    testimonial: {
      who: "Tom H., Narre Warren",
      what: "Thermann heat pump — family business feels it",
      quote:
        "Answered the phone myself, quoted the job, showed up to install the job. That trail of trust doesn't exist with most of the bigger mobs anymore.",
    },
    nearby: ["berwick", "hampton-park", "hallam", "cranbourne", "endeavour-hills"],
  },
  {
    slug: "endeavour-hills",
    name: "Endeavour Hills",
    postcode: "3802",
    distanceKm: 27,
    published: true,
    council: "City of Casey",
    landmark: "Endeavour Hills Shopping Centre on Heatherton Road and the Bemersyde Wetlands",
    housingStock:
      "80s cladded homes on standard blocks, most on their original gas ducted heating and electric-storage hot water systems — prime retrofit territory",
    commonInstall:
      "gas ducted heater replacements (usually Brivis to Braemar), and full VEU heat pump swaps replacing the original 315L electric tanks",
    localHooks: [
      "Wilandra Rise Reserve",
      "St Paul Apostle North Primary",
      "Endeavour Hills Shopping Centre",
      "the Hallam Valley Road commuter belt",
    ],
    nearby: ["hallam", "hampton-park", "narre-warren", "doveton", "dandenong"],
  },
  {
    slug: "hallam",
    name: "Hallam",
    postcode: "3803",
    distanceKm: 25,
    published: true,
    council: "City of Casey",
    landmark: "the Hallam industrial precinct along Frankston-Dandenong Road and the Hallam railway line",
    housingStock:
      "a working mix of residential streets north of the Princes Highway and the light-industrial belt south — we do both",
    commonInstall:
      "commercial and light-industrial split system fit-outs, plus residential Mitsubishi splits and continuous-flow gas hot water changeovers on the residential side",
    localHooks: [
      "Hallam Railway Station",
      "Hallam Primary",
      "the Hallam industrial precinct",
      "M-City retail across the highway",
    ],
    nearby: ["endeavour-hills", "hampton-park", "narre-warren", "doveton", "dandenong"],
  },
  {
    slug: "hampton-park",
    name: "Hampton Park",
    postcode: "3976",
    distanceKm: 24,
    published: true,
    council: "City of Casey",
    landmark: "Hampton Park Shopping Centre and the Hampton Park Wetlands",
    housingStock:
      "80s and 90s Ryan Homes estates — mostly brick veneer on standard 500-600m² blocks, with original hot water and heating still in place on a lot of them",
    commonInstall:
      "iStore 270L heat pumps replacing original electric-storage tanks — this is the max-VEU-rebate postcode where the rebate + trade-in gets the install price well under $500 out of pocket",
    localHooks: [
      "Hampton Park Secondary",
      "Coral Park Primary",
      "Hampton Park Shopping Centre",
      "Hampton Park lakes reserve",
    ],
    nearby: ["narre-warren", "hallam", "lynbrook", "cranbourne", "endeavour-hills"],
  },
  {
    slug: "cranbourne",
    name: "Cranbourne",
    postcode: "3977",
    distanceKm: 22,
    published: true,
    council: "City of Casey",
    landmark: "Royal Botanic Gardens Cranbourne and the Cranbourne Racecourse",
    housingStock:
      "a real mix — the old Cranbourne township weatherboards near the station, plus the Cranbourne North and Cranbourne East estates built through the 2010s",
    commonInstall:
      "multi-head Mitsubishi Electric splits in the family homes on the newer estates, and VEU-funded heat pump swaps on the original 1980s Cranbourne stock",
    localHooks: [
      "Royal Botanic Gardens Cranbourne",
      "Cranbourne Park Shopping Centre",
      "Cranbourne West Primary",
      "Casey Hospital (short drive)",
    ],
    testimonial: {
      who: "Priya S., Cranbourne",
      what: "Mitsubishi split install — no surprises on the invoice",
      quote:
        "Quote number matched the invoice exactly. No 'we hit unexpected wiring' story at the end. Nice change.",
    },
    nearby: ["cranbourne-east", "cranbourne-north", "clyde-north", "hampton-park", "botanic-ridge"],
  },
  {
    slug: "clyde-north",
    name: "Clyde North",
    postcode: "3978",
    distanceKm: 28,
    published: true,
    council: "City of Casey",
    landmark: "the Eliston, Meridian and Berwick Waters estates on the eastern edge of Casey's growth corridor",
    housingStock:
      "almost all post-2018 new builds — big double-storey family homes with ducted heating and cooling roughed in from day one",
    commonInstall:
      "Zonemate zoning upgrades on 4-zone ducted systems that came with the estate build, plus VEU heat pump hot water swaps as owners hit their first tank replacement",
    localHooks: [
      "Clyde Primary School",
      "Meridian Shopping Centre",
      "Berwick Waters wetland corridor",
      "the Casey Fields sports precinct",
    ],
    nearby: ["cranbourne", "cranbourne-east", "clyde", "botanic-ridge", "hampton-park"],
  },
  {
    slug: "drouin",
    name: "Drouin",
    postcode: "3818",
    distanceKm: 42,
    published: true,
    council: "Baw Baw Shire Council",
    landmark: "the Drouin township along Princes Way and Bellbird Park on the north side",
    housingStock:
      "a mix of rural residential acreage on the east and south, plus the newer estate growth pushing out toward Longwarry on the west",
    commonInstall:
      "ducted aircon installs into new-builds on the west-side estates, and larger 315L Thermann or Reclaim heat pump tanks on the acreage properties where the family draw is heavier",
    localHooks: [
      "Drouin Secondary College",
      "Drouin West Primary",
      "Bellbird Park",
      "the West Gippsland Hospital catchment",
    ],
    nearby: ["warragul", "longwarry", "bunyip", "garfield"],
  },
  {
    slug: "warragul",
    name: "Warragul",
    postcode: "3820",
    distanceKm: 48,
    published: true,
    council: "Baw Baw Shire Council",
    landmark: "the West Gippsland Arts Centre and the Warragul CBD around Queen Street",
    housingStock:
      "the regional centre for the shire — Federation weatherboards in the old town core, brick veneer through the 90s and 2000s, and new estate growth on the north edge",
    commonInstall:
      "Reclaim R290 heat pumps — the cold-morning performance actually matters this far east — and Kaden ducted systems where the customer wants the ducted feel without the Mitsubishi Diamond premium",
    localHooks: [
      "Warragul Regional College",
      "St Paul's Anglican Grammar",
      "West Gippsland Hospital",
      "the Warragul Saturday market",
    ],
    nearby: ["drouin", "longwarry", "bunyip", "garfield"],
  },

  // -------------------- Wave 2 (drafted, unpublished) --------------------

  {
    slug: "pakenham-upper",
    name: "Pakenham Upper",
    postcode: "3810",
    distanceKm: 8,
    published: false,
    council: "Cardinia Shire Council",
    landmark: "the Toomuc Valley and Beaconsfield Emerald Road ridge",
    housingStock: "semi-rural acreage properties, most on tank hot water and LPG",
    commonInstall: "LPG continuous-flow hot water swaps and larger 315L heat pumps on the acreage",
    localHooks: ["Toomuc Valley Reserve", "Cardinia Reservoir Park"],
    nearby: ["pakenham", "beaconsfield-upper", "beaconsfield"],
  },
  {
    slug: "officer-south",
    name: "Officer South",
    postcode: "3809",
    distanceKm: 8,
    published: false,
    council: "Cardinia Shire Council",
    landmark: "the Arcadia and Timbertop estates",
    housingStock: "post-2015 new-build family homes",
    commonInstall: "ducted aircon on new builds, VEU heat pump swaps as tanks fail",
    localHooks: ["St Brigid's Catholic Primary", "Arena Shopping Centre"],
    nearby: ["officer", "pakenham", "beaconsfield"],
  },
  {
    slug: "beaconsfield-upper",
    name: "Beaconsfield Upper",
    postcode: "3808",
    distanceKm: 12,
    published: false,
    council: "Cardinia Shire Council",
    landmark: "the Cardinia Reservoir Park",
    housingStock: "bush blocks and larger rural residential parcels",
    commonInstall: "split-system focus — Mitsubishi MSZ-AP and MSZ-FH for winter performance",
    localHooks: ["Cardinia Reservoir Park", "Emerald Golf Club"],
    nearby: ["beaconsfield", "emerald", "pakenham-upper"],
  },
  {
    slug: "narre-warren-north",
    name: "Narre Warren North",
    postcode: "3804",
    distanceKm: 22,
    published: false,
    council: "City of Casey",
    landmark: "the Casey Complex sports precinct",
    housingStock: "larger family blocks with more retrofit demand",
    commonInstall: "ducted retrofits and multi-head splits",
    localHooks: ["Casey Complex", "Narre Warren North Primary"],
    nearby: ["narre-warren", "narre-warren-south", "berwick"],
  },
  {
    slug: "narre-warren-south",
    name: "Narre Warren South",
    postcode: "3805",
    distanceKm: 22,
    published: false,
    council: "City of Casey",
    landmark: "the Casey Central shopping corridor",
    housingStock: "mid-2010s brick veneer family homes",
    commonInstall: "ducted service and Mitsubishi MXZ multi-heads",
    localHooks: ["Casey Central", "Narre Warren South P-12 College"],
    nearby: ["narre-warren", "hampton-park", "cranbourne"],
  },
  {
    slug: "lynbrook",
    name: "Lynbrook",
    postcode: "3975",
    distanceKm: 26,
    published: false,
    council: "City of Casey",
    landmark: "the Marriott Waters estate",
    housingStock: "2000s estate homes with ducted from build",
    commonInstall: "Zonemate zoning upgrades and heat pump hot water",
    localHooks: ["Lynbrook Station", "Marriott Waters lake"],
    nearby: ["hampton-park", "lyndhurst", "cranbourne"],
  },
  {
    slug: "lyndhurst",
    name: "Lyndhurst",
    postcode: "3975",
    distanceKm: 27,
    published: false,
    council: "City of Casey",
    landmark: "the Marriott Waters wetland",
    housingStock: "new estates east of Thompsons Road",
    commonInstall: "ducted aircon and VEU-eligible heat pump installs",
    localHooks: ["Lyndhurst Primary", "Marriott Waters wetland"],
    nearby: ["lynbrook", "hampton-park", "cranbourne"],
  },
  {
    slug: "doveton",
    name: "Doveton",
    postcode: "3177",
    distanceKm: 29,
    published: false,
    council: "City of Casey",
    landmark: "the Doveton Recreation Reserve",
    housingStock: "post-war fibro and brick, most on original hot water",
    commonInstall: "gas heater replacements and hot water swaps",
    localHooks: ["Doveton College", "Power Reserve"],
    nearby: ["endeavour-hills", "hallam", "dandenong"],
  },
  {
    slug: "dandenong",
    name: "Dandenong",
    postcode: "3175",
    distanceKm: 32,
    published: false,
    council: "City of Greater Dandenong",
    landmark: "Dandenong Market and the Drum Theatre",
    housingStock: "mixed housing — post-war units, weatherboards, newer high-density",
    commonInstall: "commercial split-system fit-outs on Lonsdale Street and residential hot water swaps",
    localHooks: ["Dandenong Station", "Dandenong Market", "Chisholm TAFE"],
    nearby: ["doveton", "keysborough", "noble-park", "springvale"],
  },
  {
    slug: "keysborough",
    name: "Keysborough",
    postcode: "3173",
    distanceKm: 34,
    published: false,
    council: "City of Greater Dandenong",
    landmark: "the Somerfield estate and Parkmore Shopping Centre",
    housingStock: "newer Somerfield estate + older Keysborough South stock",
    commonInstall: "ducted retrofits in Somerfield, VEU heat pump swaps in older Keysborough",
    localHooks: ["Parkmore Shopping Centre", "Somerfield estate"],
    nearby: ["dandenong", "noble-park", "springvale"],
  },
  {
    slug: "noble-park",
    name: "Noble Park",
    postcode: "3174",
    distanceKm: 33,
    published: false,
    council: "City of Greater Dandenope",
    landmark: "Noble Park Station and Ross Reserve",
    housingStock: "post-war fibro and brick veneer, older stock",
    commonInstall: "split-system upgrades and heat pump hot water swaps",
    localHooks: ["Noble Park Station", "Ross Reserve"],
    nearby: ["dandenong", "keysborough", "springvale"],
  },
  {
    slug: "springvale",
    name: "Springvale",
    postcode: "3171",
    distanceKm: 34,
    published: false,
    council: "City of Greater Dandenong",
    landmark: "Springvale Road commercial strip and Springvale Botanical Cemetery",
    housingStock: "older weatherboards and denser townhouses toward the station",
    commonInstall: "hot water swaps and small commercial split fit-outs",
    localHooks: ["Springvale Station", "Springvale Botanical Cemetery"],
    nearby: ["dandenong", "keysborough", "noble-park"],
  },
  {
    slug: "cranbourne-east",
    name: "Cranbourne East",
    postcode: "3977",
    distanceKm: 24,
    published: false,
    council: "City of Casey",
    landmark: "the Livingston and Cranbourne East estates",
    housingStock: "new-build family homes with ducted from day one",
    commonInstall: "Zonemate upgrades and VEU heat pump installs",
    localHooks: ["Cranbourne East Secondary", "Livingston estate"],
    nearby: ["cranbourne", "clyde-north", "clyde"],
  },
  {
    slug: "cranbourne-north",
    name: "Cranbourne North",
    postcode: "3977",
    distanceKm: 22,
    published: false,
    council: "City of Casey",
    landmark: "the Amstel and Grasmere estates",
    housingStock: "mid-2010s brick veneer builds",
    commonInstall: "multi-head Mitsubishi splits and heat pump hot water",
    localHooks: ["Amstel Golf Club", "Cranbourne North Primary"],
    nearby: ["cranbourne", "cranbourne-east", "hampton-park"],
  },
  {
    slug: "cranbourne-south",
    name: "Cranbourne South",
    postcode: "3977",
    distanceKm: 24,
    published: false,
    council: "City of Casey",
    landmark: "the rural fringe south of Cranbourne toward Devon Meadows",
    housingStock: "semi-rural acreage, tank and continuous-flow hot water",
    commonInstall: "larger 315L heat pump tanks and LPG continuous flow",
    localHooks: ["The Royal Botanic Gardens edge", "rural residential blocks"],
    nearby: ["cranbourne", "devon-meadows", "botanic-ridge"],
  },
  {
    slug: "cranbourne-west",
    name: "Cranbourne West",
    postcode: "3977",
    distanceKm: 25,
    published: false,
    council: "City of Casey",
    landmark: "the Selandra Rise estate",
    housingStock: "new-build family homes",
    commonInstall: "ducted retrofit tune-ups and heat pump installs",
    localHooks: ["Selandra Rise Community Hub", "Selandra Boulevard"],
    nearby: ["cranbourne", "hampton-park", "lyndhurst"],
  },
  {
    slug: "clyde",
    name: "Clyde",
    postcode: "3978",
    distanceKm: 29,
    published: false,
    council: "City of Casey",
    landmark: "the Clyde township area on Ballarto Road",
    housingStock: "growth corridor — mostly new estate builds",
    commonInstall: "ducted-from-day-one homes needing Zonemate tuning and heat pumps",
    localHooks: ["Clyde Recreation Reserve"],
    nearby: ["clyde-north", "cranbourne", "botanic-ridge"],
  },
  {
    slug: "botanic-ridge",
    name: "Botanic Ridge",
    postcode: "3977",
    distanceKm: 27,
    published: false,
    council: "City of Casey",
    landmark: "the Settlers Run Golf & Country Club",
    housingStock: "semi-rural, larger footprint homes",
    commonInstall: "multi-head splits and larger heat pump tanks",
    localHooks: ["Settlers Run Golf Club", "Royal Botanic Gardens Cranbourne"],
    nearby: ["cranbourne", "clyde", "devon-meadows"],
  },
  {
    slug: "devon-meadows",
    name: "Devon Meadows",
    postcode: "3977",
    distanceKm: 27,
    published: false,
    council: "City of Casey",
    landmark: "the Devon Meadows township",
    housingStock: "rural acreage, tank hot water common",
    commonInstall: "larger 315L heat pump tanks, LPG continuous flow",
    localHooks: ["Devon Meadows Primary", "Devon Meadows General Store"],
    nearby: ["botanic-ridge", "cranbourne-south", "pearcedale"],
  },
  {
    slug: "pearcedale",
    name: "Pearcedale",
    postcode: "3912",
    distanceKm: 33,
    published: false,
    council: "City of Casey",
    landmark: "the Pearcedale township and Coolart Wetlands",
    housingStock: "rural, LPG common, larger blocks",
    commonInstall: "LPG conversions to continuous flow, big tank heat pumps",
    localHooks: ["Coolart Wetlands", "Pearcedale Primary"],
    nearby: ["devon-meadows", "tooradin"],
  },
  {
    slug: "tooradin",
    name: "Tooradin",
    postcode: "3980",
    distanceKm: 32,
    published: false,
    council: "City of Casey",
    landmark: "the Tooradin foreshore and boat ramp",
    housingStock: "coastal-edge homes needing salt-tolerant hardware",
    commonInstall: "coastal-rated aircon units and marine-grade fittings",
    localHooks: ["Tooradin Airfield", "Sawtells Inlet"],
    nearby: ["pearcedale", "lang-lang", "koo-wee-rup"],
  },
  {
    slug: "nar-nar-goon",
    name: "Nar Nar Goon",
    postcode: "3812",
    distanceKm: 6,
    published: false,
    council: "Cardinia Shire Council",
    landmark: "the Nar Nar Goon township and the Bunyip River",
    housingStock: "rural blocks, older brick veneer, some LPG",
    commonInstall: "split systems into weatherboards, heat pump upgrades from tank",
    localHooks: ["Nar Nar Goon Primary", "Bunyip River"],
    nearby: ["pakenham", "tynong", "bunyip"],
  },
  {
    slug: "tynong",
    name: "Tynong",
    postcode: "3813",
    distanceKm: 11,
    published: false,
    council: "Cardinia Shire Council",
    landmark: "the Gumbuya World theme park",
    housingStock: "rural residential, gas and LPG mix",
    commonInstall: "LPG continuous flow and split systems",
    localHooks: ["Gumbuya World", "Tynong Railway Station"],
    nearby: ["nar-nar-goon", "bunyip", "garfield"],
  },
  {
    slug: "bunyip",
    name: "Bunyip",
    postcode: "3815",
    distanceKm: 17,
    published: false,
    council: "Cardinia Shire Council",
    landmark: "the Bunyip township and the Bunyip Football Netball Club oval",
    housingStock: "historic town centre with a retrofit-heavy older stock",
    commonInstall: "gas ducted replacements and Mitsubishi wall splits",
    localHooks: ["Bunyip Primary", "Bunyip FNC", "Bunyip State Park edge"],
    nearby: ["garfield", "tynong", "longwarry"],
  },
  {
    slug: "garfield",
    name: "Garfield",
    postcode: "3814",
    distanceKm: 14,
    published: false,
    council: "Cardinia Shire Council",
    landmark: "the Garfield township along Main Street",
    housingStock: "rural residential, standard blocks",
    commonInstall: "split systems and gas ducted heating tune-ups",
    localHooks: ["Garfield Primary", "Cannibal Creek Reserve"],
    nearby: ["tynong", "bunyip", "longwarry"],
  },
  {
    slug: "cardinia-town",
    name: "Cardinia",
    postcode: "3978",
    distanceKm: 8,
    published: false,
    council: "Cardinia Shire Council",
    landmark: "the Cardinia township and shire offices",
    housingStock: "semi-rural blocks, older brick veneer",
    commonInstall: "hot water tank swaps and split-system installs",
    localHooks: ["Cardinia Shire offices"],
    nearby: ["pakenham", "officer", "clyde"],
  },
  {
    slug: "koo-wee-rup",
    name: "Koo Wee Rup",
    postcode: "3981",
    distanceKm: 18,
    published: false,
    council: "Cardinia Shire Council",
    landmark: "the Koo Wee Rup Swamp Historical Society and the Bunyip Main Drain",
    housingStock: "farming community, LPG common",
    commonInstall: "LPG continuous flow and larger heat pump tanks for larger households",
    localHooks: ["Koo Wee Rup Secondary", "Bunyip Main Drain"],
    nearby: ["lang-lang", "tooradin", "bayles"],
  },
  {
    slug: "lang-lang",
    name: "Lang Lang",
    postcode: "3984",
    distanceKm: 30,
    published: false,
    council: "Cardinia Shire Council",
    landmark: "the Lang Lang township and Western Port coast",
    housingStock: "rural coast, tank and heat pump mix",
    commonInstall: "heat pump swaps and LPG hot water",
    localHooks: ["Lang Lang Primary", "Western Port bay"],
    nearby: ["koo-wee-rup", "tooradin"],
  },
  {
    slug: "bayles",
    name: "Bayles",
    postcode: "3981",
    distanceKm: 20,
    published: false,
    council: "Cardinia Shire Council",
    landmark: "the Bayles township",
    housingStock: "farming, low-density",
    commonInstall: "LPG continuous flow and heat pump storage",
    localHooks: ["Bayles Fauna Park"],
    nearby: ["koo-wee-rup", "yannathan"],
  },
  {
    slug: "yannathan",
    name: "Yannathan",
    postcode: "3981",
    distanceKm: 22,
    published: false,
    council: "Cardinia Shire Council",
    landmark: "the Yannathan township",
    housingStock: "rural, LPG common",
    commonInstall: "LPG continuous flow, larger heat pump tanks",
    localHooks: ["Yannathan Primary", "Lang Lang River"],
    nearby: ["bayles", "koo-wee-rup", "lang-lang"],
  },
  {
    slug: "longwarry",
    name: "Longwarry",
    postcode: "3816",
    distanceKm: 27,
    published: false,
    council: "Baw Baw Shire Council",
    landmark: "the Longwarry township",
    housingStock: "rural residential",
    commonInstall: "ducted retrofits and heat pump hot water",
    localHooks: ["Longwarry Primary", "Longwarry Football Club"],
    nearby: ["drouin", "bunyip", "garfield"],
  },
  {
    slug: "emerald",
    name: "Emerald",
    postcode: "3782",
    distanceKm: 27,
    published: false,
    council: "Cardinia Shire Council",
    landmark: "the Dandenong Ranges and Puffing Billy Railway",
    housingStock: "hills homes, older cottages and larger newer builds",
    commonInstall: "Reclaim R290 heat pumps for cold-climate performance, Mitsubishi MSZ-FH Hyper Heating splits",
    localHooks: ["Puffing Billy Railway", "Emerald Lake Park", "Emerald Secondary"],
    nearby: ["gembrook", "cockatoo", "beaconsfield-upper"],
  },
  {
    slug: "cockatoo",
    name: "Cockatoo",
    postcode: "3781",
    distanceKm: 25,
    published: false,
    council: "Cardinia Shire Council",
    landmark: "the Cockatoo township in the Dandenong Ranges",
    housingStock: "hills homes, cool climate",
    commonInstall: "cold-climate splits (Mitsubishi FH) and heat pumps built for cold mornings",
    localHooks: ["Cockatoo Primary", "Wright Forest"],
    nearby: ["emerald", "gembrook", "beaconsfield-upper"],
  },
  {
    slug: "gembrook",
    name: "Gembrook",
    postcode: "3783",
    distanceKm: 26,
    published: false,
    council: "Cardinia Shire Council",
    landmark: "the Gembrook township and Puffing Billy terminus",
    housingStock: "hills, larger bush blocks",
    commonInstall: "R290 heat pumps and Hyper Heating splits, LPG changeovers",
    localHooks: ["Puffing Billy Gembrook Station", "Bunyip State Park"],
    nearby: ["emerald", "cockatoo"],
  },
];

export const publishedSuburbs: Suburb[] = suburbs.filter((s) => s.published);

export type SuburbSlug = (typeof suburbs)[number]["slug"];
